apiVersion: v1
kind: Service
metadata:
   name: service-aubay-movie-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: aubay-movie-app-pod
  

---

apiVersion: v1
kind: Pod
metadata:
  name: aubay-movie-app-pod
  labels:
    app: aubay-movie-app-pod
spec:
  containers: 
    - name: aubay-movie-app-container
      image: americanolinhares/java-docker:latest
      ports: 
      - containerPort: 8080   
      livenessProbe:
        httpGet:
          path: "/actuator/health/liveness"
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: "/actuator/health/readiness"
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3